os: osx
osx_image: xcode10.2
language: objective-c
env:
  global:
  - THEOS=~/theos
before_install:
  - brew update
  - brew install dpkg ldid
  - wget https://qwertyuiop1379.github.io/iPhoneOS11.2.sdk.zip
  - git clone --recursive git://github.com/theos/theos.git ~/theos
  - unzip iPhoneOS11.2.sdk.zip -d ~/theos/sdks/iPhoneOS11.2.sdk
script:
  - "export SYSROOT=~/theos/sdks/iPhoneOS11.2.sdk/"
  - "export VERSION=$(grep 'Version: ' control | sed 's/^.*: //')"
  - "export DESCRIPTION=$(awk '/## v$VERSION/{getline; print}' README.md)"
  - "export FILENAME='packages/'\"$(grep 'Package: ' control | sed 's/^.*: //')\"'_'\"$VERSION\"'_iphoneos-arm.deb'"
  - make package
before_deploy:
  - git config --local user.name "Jeff Rescignano"
  - git config --local user.email "jeff@jeffresc.com"
  - git tag -a v$VERSION -m "$DESCRIPTION"
deploy:
  provider: releases
  token:
    secure: JWWhwScqvPF2kxiB8tqVGtVNK4sr8ULFZwtu6G2CLXGyPyqRoSVAP1XkVA1us2TtDAkTegsMvLBvxKaHyVwZHtuUbyuBOndfd51QOBgVX/WDZ+2Adpmvex82RH2G0aqNG5Ie0h0EYKFyE7GI2FKPprkygvQg+ja2WX3/h9bVxTXuZcgbCIFkvzv0BFQFP8DpVW5QsWFwSB2Tl+YHXAzJqkV7sKjLK42u4ATybw2TTCqqZC+3uP3UlvjxUQGC5AMvrpRfQ9RY64vNoHryrsYw2fX06P+MKcenNwaYarC6LsZbYBpEumjqh1Rd80emnnRIpHuIGaemlcW5rFCMwGEQPa8wgJvkSSzHCnTByLNMxBSyOQU3CcNDG+i46WzqKYpWnRy4A0RBc8FZ8GYCTlakc2RmFZq1QIDRFTJc6OyfQyi6sHw/Zc31uXjljMoNK19UnPmWO/HUy8HRKhHYwFS/cjufg3ub7WdM/yRxzE3huhbExge6AldoDWwhasfAu7M2x0ovWMtejAYGi9eGlSiiUQlVGg+DhkaE/VT3IqVuMScTwGs4MThTJl84AgK+Jjm2h+bkPtpwjtC9JOLF1lWGjI+QoYcNrm6w6zY/1e4/IuIeFv3HAXHUDY/egAjH3/i8QM9zh61Is4CIEJGyoOllL5MO3TaAc2o8rDD1yCm7I6c=
  file: $FILENAME
  on:
    branches:
      only:
        - master
branches:
  except:
  - /^untagged/
